# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Yet another blog
email: r11baka at gmail com
description: > # this means to ignore newlines until "baseurl:"
  Еще 1 блог о IT
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://r11baka.github.io/" # the base hostname & protocol for your site
github_username:  r11baka
google_analytics: UA-80976120-1
github: [metadata]
# Build settings
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1
highlighter: rouge
exclude: [vendor]

plugins_dir: ./_scripts
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag

theme: jekyll-theme-cayman
